@url = tfgrid.workloads.reservation.volume.1
size = (I)
type = "HDD,SSD" (E)
#where to send the statistics too
stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
info = (O) !tfgrid.workloads.reservation.info.1
