

@url = tfgrid.workloads.reservation.zdb.1
size = (I)
mode = "seq,user" (E)
password = (S)
disk_type = "hdd,ssd" (E)
public = false (B)
#where to send the statistics too
stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
info = (O) !tfgrid.workloads.reservation.info.1
